Quest1
devpass-tech/devquest-gustavo-fernandes pull request #2
Opened 2022-08-17 02:26 UTC by GustavoFernandesBatista

2022-08-17 17:01 UTC, rdgborges requested changes

2022-08-17 17:01 UTC, rdgborges commented on quests/challenge-github-app/GitHubApp/Screens/Components/EmptyView.swift
> +            self.subtitleEmptyMessageLabel.topAnchor.constraint(equalTo: self.emptyMessageLabel.bottomAnchor , constant: 8),
É uma boa solução posicionar a subtitleEmptyMessageLabel logo abaixo da emptyMessageLabel usando topAnchor e bottomAnchor.

Uma outra possibilidade é utilizar uma StackView, que podemos aplicar na próxima tarefa (LoadingView).

2022-08-17 17:01 UTC, rdgborges commented on quests/challenge-github-app/GitHubApp/Screens/Components/LoadingView.swift
> +//
Como esse código não está sendo utilizado e se refere à outra tarefa, pode removê-lo?

2022-08-19 19:40 UTC, GustavoFernandesBatista commented on quests/challenge-github-app/GitHubApp/Screens/Components/EmptyView.swift
> +            self.subtitleEmptyMessageLabel.topAnchor.constraint(equalTo: self.emptyMessageLabel.bottomAnchor , constant: 8),
@rdgborges não entendi, vc poderia demonstrar o jeito ideal ?

2022-08-19 19:46 UTC, GustavoFernandesBatista commented on quests/challenge-github-app/GitHubApp/Screens/Components/LoadingView.swift
> +//
removido

2022-08-22 17:40 UTC, rdgborges commented on quests/challenge-github-app/GitHubApp/Screens/Components/EmptyView.swift
> +            self.subtitleEmptyMessageLabel.topAnchor.constraint(equalTo: self.emptyMessageLabel.bottomAnchor , constant: 8),
Vou demonstrar na outra task. ;)

2022-08-22 17:41 UTC, rdgborges approved these changes

2022-08-22 17:41 UTC, merged