Quest2
devpass-tech/devquest-gustavo-fernandes pull request #3
Opened 2022-08-19 20:18 UTC by GustavoFernandesBatista

2022-08-22 17:45 UTC, rdgborges requested changes

2022-08-22 17:45 UTC, rdgborges commented on quests/challenge-github-app/GitHubApp/Screens/Components/LoadingView.swift
> +        label.translatesAutoresizingMaskIntoConstraints = false
Dica: como a label é adiciona em uma UIStackView, você só precisa configurar as constraints da stack. Dessa forma, não há necessidade de adicionar essa linha.

Vamos remover a linha?

2022-08-23 20:02 UTC, GustavoFernandesBatista commented on quests/challenge-github-app/GitHubApp/Screens/Components/LoadingView.swift
> +        label.translatesAutoresizingMaskIntoConstraints = false
removido

2022-08-24 13:39 UTC, rdgborges approved these changes

2022-08-24 13:39 UTC, merged