Quest4
devpass-tech/devquest-gustavo-fernandes pull request #5
Opened 2022-08-22 05:18 UTC by GustavoFernandesBatista

2022-08-25 17:45 UTC, rdgborges requested changes
Adicionar screenshot do componente renderizado na tela na descrição do PR.

2022-08-25 17:45 UTC, rdgborges commented on quests/challenge-github-app/GitHubApp/Screens/Components/RepositoryCellView.swift
> +        self.setupConstraints()
O método `setupConstraints` está sendo chamado duas vezes. Uma aqui e outra dentro do método `setupView`.

2022-08-25 17:45 UTC, rdgborges commented on quests/challenge-github-app/GitHubApp/Screens/Components/RepositoryCellView.swift
> +        contentView.addSubview(stackView)
É uma boa prática separar o código de criação de subviews da criação das constraints. Recomendo você criar um novo método `func addSubviews()`, passar essa linha para lá e chamar o novo método dentro do método `setupViews`, antes de configurar as constraints.

2022-08-25 19:20 UTC, GustavoFernandesBatista commented on quests/challenge-github-app/GitHubApp/Screens/Components/RepositoryCellView.swift
> +        self.setupConstraints()
removido

2022-08-25 19:23 UTC, GustavoFernandesBatista commented on quests/challenge-github-app/GitHubApp/Screens/Components/RepositoryCellView.swift
> +        contentView.addSubview(stackView)
Rodrigo estudei um novo metodo criando um protocol chamado ViewConfiguration que facilita e organiza a criação de subviews, o que vc acha ?

2022-08-25 19:39 UTC, rdgborges commented on quests/challenge-github-app/GitHubApp/Screens/Components/RepositoryCellView.swift
> +        contentView.addSubview(stackView)
Muito bom! É um padrão bastante utilizado. 👏

2022-08-25 19:42 UTC, rdgborges requested changes

2022-08-25 19:42 UTC, rdgborges commented on quests/challenge-github-app/GitHubApp/Screens/Components/RepositoryCellView.swift
> +
Acredito que está faltando você configurar o `accessoryType`, essa seta que fica no lado direito:
<img width="422" alt="Screen Shot 2022-08-25 at 16 41 16" src="https://user-images.githubusercontent.com/1377307/186753739-290f10b5-916c-4466-ad20-c2febe5ec31c.png">

Você consegue fazer isso com `self.accessoryType = .disclosureIndicator`

2022-09-05 12:47 UTC, rdgborges approved these changes

2022-09-05 12:47 UTC, merged